name: Update Music Status

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-music:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with current time
        run: |
          echo "Last updated: $(date)" > music_status.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add music_status.txt
          git commit -m "Update music status" || exit 0
          git push
